theme = "hugo-theme-dream"
baseurl = "https://shrishtivaish-rblogs.netlify.app/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "R Blogs"
googleAnalytics = "UA-172540293-1"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableRobotsTXT = true

[params.adsense]
   client = "ca-pub-4041306379715431"

[permalinks]
   posts = "/:year/:month/:slug/"
    
[taxonomies]
  tag = "tags"
  category = "categories"

[markup]
  [markup.highlight]
    codeFences = true
    style = "friendly"


[params]
enableSearch = true
backgroundImage = "/img/cover.png"
author = "Shrishti Vaish"

rss = true

email = "shrishtiport89@gmail.com"
twitter = "ShrishtiVaish"
instagram = "rblogs_ShrishtiVaish"
github = "shrish83"
linkedin = "shrishti-vaish"
NewsletterSignup = "shrish"


siteStartYear = 2020

favicon = "/fav.ico"

[outputs]
  home = ["HTML", "RSS", "JSON"]

#options
showSummaryCoverInPost = true